# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        #comentar si se quiere usar bd
        #Symfony\Component\Security\Core\User\User:
        #    algorithm: md5
        #    encode_as_base64: false
        #    iterations: 0
        #comentar si se quiere usar memoria quemada (y se necesita cambiar alortimo de encrypción)
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
            #algorithm: md5
            #encode_as_base64: false
            #iterations: 0

    #jerarquia de roles ADMIN>USER
    role_hierarchy:
        ROLE_ADMIN: 'ROLE_USER'
    providers:
        #usuario quemado
        #in_memory:
        #    memory:
        #        users:
        #            memory:
        #                password: '$2a$12$SgKol5wgx0lKldG8Ek2rKO4ZhydDlMIgrnnaQGT3FXkx4/qm.hd.G'
        #                roles: 'ROLE_ADMIN'
        #            someuser:
        #                password: '$2a$12$SgKol5wgx0lKldG8Ek2rKO4ZhydDlMIgrnnaQGT3FXkx4/qm.hd.G'
        #                roles: 'ROLE_USER'
        #usuario en base de datos (query en UserRepository.php)
        pgsql:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage

            #descomentar para permitir conexion a bd!!
            pattern: ^/
            http_basic:
                provider: pgsql

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
